### ISSUE TITLE
patch to make_chroot_initrd work for ubuntu 16.04 derivative (Linux Mint 18.3)

### ISSUE THREAD

**Issue by mariowil7** [lemonsqueeze/boot-chroot#4]
Instead of **$script_dir** use **$cwd** and the script will work like a charm, see the code below:

echo "patching"
patch --silent --dry-run -p1 < "**$cwd/initrd.patch**" >/dev/null && \
patch --silent -p1 < "**$cwd/initrd.patch**"	|| \
patch --silent -p1 < "**$cwd/initrd_1604.patch**" || die "patch failed !"

**Comment by lemonsqueeze** [comment]
Fixed in 0c9924f, thanks
